"""Replay driver (module C6): treat day 1-200 as history, day 200-365 as replay.

For every session (default every 7 sim days from day 200):
  1. jump the plant API clock to the session's as-of (if a server is reachable)
  2. prepare the anomaly table (scripts/prepare_anomaly_table.py) and score it
     with models.anomaly (7-day window)
  3. score the predict artefact at as-of with models.predict (features <= as-of only)
  4. append one row to reports/replay_log.md and reports/replay/sessions.json

This script NEVER reads ground truth. Lead times and GO/NO-GO are added to the
log by the validator afterwards.

    uv run python scripts/replay.py --predict-artifact predict_fleet_h30_2024-10-15_s42
    uv run python scripts/replay.py --from-day 200 --to-day 365 --step-days 7
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path

import pandas as pd

from models.anomaly import run_score as anomaly_score
from models.predict.model import load_artifact, score as predict_score
from plant import cli as plantctl

START = datetime(2024, 1, 1)
LOG = Path("reports/replay_log.md")
SESSION_DIR = Path("reports/replay")
ARTIFACT_DIR = Path("models/artifacts/replay")
FEATURES = Path("data/derived/predict_features_2024-12-30.parquet")


def day_to_ts(day: int) -> datetime:
    return START + timedelta(days=day)


def jump_clock(as_of: datetime) -> str:
    code, text = plantctl.run(["--admin", "jump", "--to", as_of.isoformat()])
    return "jumped" if code == 0 else f"skipped ({text.splitlines()[0][:60]})"


def prepare_table(as_of: datetime, lookback_days: int) -> Path:
    date = as_of.strftime("%Y-%m-%d")
    out = Path("data/derived") / f"anomaly_fleet_{date}.parquet"
    if not out.exists():
        subprocess.run(
            [sys.executable, "scripts/prepare_anomaly_table.py", "--as-of", as_of.isoformat(), "--lookback-days", str(lookback_days)],
            check=True, capture_output=True, text=True,
        )
    return out


def session(day: int, art: dict, feats: pd.DataFrame, window_days: int, lookback_days: int, do_jump: bool) -> dict:
    as_of = day_to_ts(day)
    clock = jump_clock(as_of) if do_jump else "not attempted"
    table = prepare_table(as_of, lookback_days)
    an = anomaly_score(as_of.isoformat(), window_days=window_days, input_path=str(table), report_dir=SESSION_DIR, artifact_dir=ARTIFACT_DIR)
    ranked = predict_score(art, feats, as_of, report_dir=SESSION_DIR)
    flags = [
        {"asset": f["asset"], "tag": f["tag"], "first_flag_ts": pd.Timestamp(f["first_flag_ts"]).isoformat(),
         "severity": round(f["severity"], 2), "interpretation": f["interpretation"]}
        for f in an["flags"]
    ]
    top = ranked.iloc[0]
    return {
        "day": day,
        "as_of": as_of.isoformat(),
        "clock": clock,
        "anomaly_run_id": an["run_id"],
        "anomaly_flags": flags,
        "anomaly_assets": sorted({f["asset"] for f in flags}),
        "predict_run_id": art["run_id"],
        "predict_top": {"asset": top["asset"], "p_fail": round(float(top["p_fail"]), 3), "interpretation": top["interpretation"]},
        "predict_alerts": ranked.loc[ranked["alert"], "asset"].tolist(),
        "predict_all": {r["asset"]: round(float(r["p_fail"]), 3) for _, r in ranked.iterrows()},
    }


def write_log(sessions: list[dict], art: dict, args: argparse.Namespace) -> None:
    SESSION_DIR.mkdir(parents=True, exist_ok=True)
    (SESSION_DIR / "sessions.json").write_text(json.dumps(sessions, indent=2), encoding="utf-8")
    first_seen: dict[str, str] = {}
    lines = [
        "# Replay log",
        "",
        f"History: sim day 1-{args.from_day}. Replay: day {args.from_day}-{args.to_day}, one session every {args.step_days} days. "
        f"Generated by `scripts/replay.py` on {datetime.now():%Y-%m-%d %H:%M}; this script never reads ground truth.",
        "",
        f"- Anomaly: `models.anomaly` (30-day rolling z, |z|>3 for 6+ h, {args.window_days}-day scoring window), no training.",
        f"- Predict: artefact `{art['run_id']}` (cutoff {art['cutoff'][:10]}, training data ends {art['split']['train_end'][:10]}). "
        f"Sessions at or before day {(pd.Timestamp(art['cutoff']) - START).days} overlap its training period and are in-sample for predict.",
        "- Per-session reports: `reports/replay/anomaly_<date>.md`, `reports/replay/predict_<date>.md`. Machine-readable: `reports/replay/sessions.json`.",
        "",
        "## Sessions",
        "",
        "| # | day | as-of | anomaly flags (asset.tag sev) | first flag per asset | predict top (p) | predict alerts | validator |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for i, s in enumerate(sessions, 1):
        for f in s["anomaly_flags"]:
            first_seen.setdefault(f["asset"], f"{f['first_flag_ts'][:10]} (day {(pd.Timestamp(f['first_flag_ts']) - START).days})")
        by_tag: dict[str, float] = {}
        for f in s["anomaly_flags"]:
            by_tag[f["tag"]] = max(by_tag.get(f["tag"], 0), f["severity"])
        flags_txt = ", ".join(f"{t} {v:.1f}" for t, v in sorted(by_tag.items())) or "-"
        firsts = "; ".join(f"{a}: {d}" for a, d in first_seen.items() if a in s["anomaly_assets"]) or "-"
        pt = s["predict_top"]
        lines.append(
            f"| {i} | {s['day']} | {s['as_of'][:10]} | {flags_txt} | {firsts} | {pt['asset']} ({pt['p_fail']:.2f}) | "
            f"{', '.join(s['predict_alerts']) or '-'} | pending |"
        )
    lines += [
        "",
        "## First anomaly flag per asset (cumulative over the replay)",
        "",
    ] + [f"- **{a}**: {d}" for a, d in sorted(first_seen.items())] + [
        "",
        "## Validator verdict",
        "",
        "_pending: run the validator subagent; it reveals ground truth, scores lead time per scripted failure and false alerts per asset-month, and returns GO/NO-GO per model. Paste its output here._",
        "",
    ]
    LOG.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--from-day", type=int, default=200)
    ap.add_argument("--to-day", type=int, default=365)
    ap.add_argument("--step-days", type=int, default=7)
    ap.add_argument("--window-days", type=int, default=7)
    ap.add_argument("--lookback-days", type=int, default=45, help="history pulled for the anomaly baseline")
    ap.add_argument("--predict-artifact", default="predict_fleet_h30_2024-10-15_s42")
    ap.add_argument("--features", default=str(FEATURES))
    ap.add_argument("--no-jump", action="store_true", help="do not move the API clock")
    args = ap.parse_args(argv)

    art = load_artifact(args.predict_artifact)
    feats = pd.read_parquet(args.features)
    max_day = min(args.to_day, 364)  # data ends 2024-12-30
    sessions = []
    for day in range(args.from_day, max_day + 1, args.step_days):
        s = session(day, art, feats, args.window_days, args.lookback_days, not args.no_jump)
        sessions.append(s)
        print(f"day {day:3d} {s['as_of'][:10]}  anomaly: {', '.join(s['anomaly_assets']) or '-':12s}  "
              f"predict top: {s['predict_top']['asset']} {s['predict_top']['p_fail']:.2f}  alerts: {', '.join(s['predict_alerts']) or '-'}  clock {s['clock']}")
    write_log(sessions, art, args)
    print(f"wrote {LOG.as_posix()} and {(SESSION_DIR / 'sessions.json').as_posix()}")


if __name__ == "__main__":
    main()
